version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ../db-data:/var/lib/mysql
    ports:
      - "3309:3306"